name = "Joshcraft"
author = "Chedd"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "232409fd3d8b0f8284d52337291cc6aeeb11e86fc6ede586c10f807914328c2b"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
