name = "Joshcraft"
author = "Chedd"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc7c9488672f74cd212622eb9dc15a5673df5b0bd2893f380844148262b8db0a"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
