name = "Joshcraft"
author = "Chedd"
version = "1.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e0694506d2afbd1ba00d57a56cd62be54214e0b42eeef40499eecf7fe4ea0bb"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"

[options]
acceptable-game-versions = []
